services:


  # nats-hub:
  #   image: nats:2.8.4
  #   container_name: nats-hub
  #   volumes:
  #     - ./nats.conf:/etc/nats/nats.conf  # Mount the configuration file
  #   ports:
  #     - "7422:4222"  # NATS client connections
  #     - "7423:6222"  # NATS cluster communication
  #     - "7424:8222"  # NATS monitoring
  #     - "7425:7422"  # NATS leaf node connections (this maps the leaf node listening port)
  #   command: >
  #     -c /etc/nats/nats.conf
  #   environment:
  #     - NATS_SERVER_NAME=hub

      
  nats-node1:
    build: .
    container_name: nats-node1
    volumes:
      - ./leaf-node.creds:/etc/nats/leaf-node.creds
    environment:
      - NATS_SERVER_NAME=node1
      - NATS_SERVER_PORT=4222
      - NATS_CLUSTER_PORT=6222
      - NATS_CLUSTER_PEERS=nats://nats-node2:6222
    ports:
      - "4222:4222"
      - "8222:8222"

  nats-node2:
    build: .
    container_name: nats-node2
    volumes:
      - ./leaf-node.creds:/etc/nats/leaf-node.creds
    environment:
      - NATS_SERVER_NAME=node2
      - NATS_SERVER_PORT=4223
      - NATS_CLUSTER_PORT=6222
      - NATS_CLUSTER_PEERS=nats://nats-node1:6222
    ports:
      - "4223:4223"
      - "8223:8223"

  nats-node3:
    build: .
    container_name: nats-node3
    volumes:
      - ./leaf-node.creds:/etc/nats/leaf-node.creds
    environment:
      - NATS_SERVER_NAME=node3
      - NATS_SERVER_PORT=4224
      - NATS_CLUSTER_PORT=6222
      - NATS_CLUSTER_PEERS=nats://nats-node1:6222
    ports:
      - "4224:4224"
      - "8224:8224"


  #   # Create one client node for nats client to connect to the cluster and test the communication
  # nats-client:
  #   build: .
  #   container_name: nats-client
  #   environment:
  #     - NATS_SERVER_NAME=client
  #     - NATS_SERVER_PORT=4225
  #     - NATS_CLUSTER_PORT=6222
  #     - NATS_CLUSTER_PEERS=nats://nats-node1:6222,nats://nats-node2:6222,nats://nats-node3:6222
  #   ports:
  #     - "4225:4225"
  #     - "8225:8225"







 