services:
  nats-hub1:
    image: nats:2.8.4
    container_name: nats-hub1
    volumes:
      - ./nats.conf:/etc/nats/nats.conf  # Mount the configuration file
    ports:
      - "4222:4222"  # NATS client connections (only exposing this hub externally)
    command: >
      -c /etc/nats/nats.conf --server_name=hub1 -p 4222
    environment:
      - NATS_SERVER_NAME=hub1
    networks:
      - nats-network
  
  nats-hub2:
    image: nats:2.8.4
    container_name: nats-hub2
    volumes:
      - ./nats.conf:/etc/nats/nats.conf  # Mount the configuration file
    command: >
      -c /etc/nats/nats.conf --server_name=hub2 -p 4222
    environment:
      - NATS_SERVER_NAME=hub2
    networks:
      - nats-network

  nats-hub3:
    image: nats:2.8.4
    container_name: nats-hub3
    volumes:
      - ./nats.conf:/etc/nats/nats.conf  # Mount the configuration file
    command: >
      -c /etc/nats/nats.conf --server_name=hub3 -p 4222
    environment:
      - NATS_SERVER_NAME=hub3
    networks:
      - nats-network

  nats-node1:
    build: .
    container_name: nats-node1
    volumes:
      - ./leaf-node.creds:/etc/nats/leaf-node.creds
    environment:
      - NATS_SERVER_NAME=node1
      - NATS_SERVER_PORT=4222
      - NATS_CLUSTER_PORT=6222
      # - NATS_CLUSTER_PEERS=nats://nats-node2:6222
    networks:
      - nats-network

  nats-node2:
    build: .
    container_name: nats-node2
    volumes:
      - ./leaf-node.creds:/etc/nats/leaf-node.creds
    environment:
      - NATS_SERVER_NAME=node2
      - NATS_SERVER_PORT=4223
      - NATS_CLUSTER_PORT=6222
      # - NATS_CLUSTER_PEERS=nats://nats-node1:6222
    networks:
      - nats-network

  nats-node3:
    build: .
    container_name: nats-node3
    volumes:
      - ./leaf-node.creds:/etc/nats/leaf-node.creds
    environment:
      - NATS_SERVER_NAME=node3
      - NATS_SERVER_PORT=4224
      - NATS_CLUSTER_PORT=6222
      # - NATS_CLUSTER_PEERS=nats://nats-node1:6222
    networks:
      - nats-network

networks:
  nats-network:
    driver: bridge